version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
    - 14.14.22
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
  - dependency-name: "@sentry/browser"
    versions:
    - 5.29.2
    - 6.0.3
    - 6.2.0
    - 6.2.1
  - dependency-name: "@types/react-router-dom"
    versions:
    - 5.1.7
  - dependency-name: react-router-dom
    versions:
    - 5.2.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
  - dependency-name: prettier
    versions:
    - 1.19.1
    - 2.2.1
  - dependency-name: react-tooltip
    versions:
    - 4.2.11
    - 4.2.13
    - 4.2.14
    - 4.2.15
  - dependency-name: react-ga
    versions:
    - 3.3.0
  - dependency-name: react-redux
    versions:
    - 7.2.2
  - dependency-name: react-facebook
    versions:
    - 8.1.4
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.2.2
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.2
  - dependency-name: connected-react-router
    versions:
    - 6.9.1
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: react
    versions:
    - 16.14.0
  - dependency-name: redux-form
    versions:
    - 8.3.7
  - dependency-name: history
    versions:
    - 4.10.1
  - dependency-name: moment
    versions:
    - 2.29.1
  - dependency-name: react-dom
    versions:
    - 16.13.0
  - dependency-name: redux
    versions:
    - 4.0.5
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.0
    - 3.3.1
  - dependency-name: enzyme-adapter-react-16
    versions:
    - 1.15.5
    - 1.15.6
  - dependency-name: enzyme
    versions:
    - 3.11.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
  - dependency-name: eslint-plugin-import
    versions:
    - 2.22.1
  - dependency-name: eslint-plugin-jsx-a11y
    versions:
    - 6.4.1
  - dependency-name: array.prototype.find
    versions:
    - 2.1.1
  - dependency-name: qs
    versions:
    - 6.9.4
    - 6.9.6
  - dependency-name: promise
    versions:
    - 8.1.0
  - dependency-name: "@types/react-redux"
    versions:
    - 7.1.15
    - 7.1.16
  - dependency-name: bootstrap
    versions:
    - 4.5.3
  - dependency-name: react-global-configuration
    versions:
    - 1.4.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
  - dependency-name: "@types/enzyme"
    versions:
    - 3.10.8
  - dependency-name: http-proxy
    versions:
    - 1.18.1
  - dependency-name: dot-prop
    versions:
    - 4.2.1
  - dependency-name: express-http-proxy
    versions:
    - 1.6.2
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: node-sass
    versions:
    - 4.14.1
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: retranslate
    versions:
    - 1.2.0
  - dependency-name: acorn
    versions:
    - 5.7.4
  - dependency-name: babel-eslint
    versions:
    - 10.1.0
  - dependency-name: react-test-renderer
    versions:
    - 16.13.0
  - dependency-name: eslint
    versions:
    - 6.8.0
  - dependency-name: redux-mock-store
    versions:
    - 1.5.4
